### PR TITLE
🌟 new: Adds preflight tests via Nightwatch (second attempt)

### PR DESCRIPTION
**Pull request by aendrew**
Because #18 was opened against `ft-interactive#ig-article` instead of `master`, I've opened this new PR so it can merge cleanly.

This adds Nightwatch/Selenium and has about ~50 assertions to check the main meta tags are all filled.

### CODE REVIEW

**Comment by aendrew** [comment]
Noticed Circle's NodeJS was downgraded in one of the earlier commits; have pushed a new commit commit that does likewise so that `gulp-sass` doesn't fail.

**Comment by aendrew** [comment]
Moved the new dependencies to `optionalDependencies` so they can be avoided locally by specifying `npm install --no-optional`.

**Comment by aendrew** [comment]
Moved the new dependencies to `optionalDependencies` so they can be avoided locally by specifying `npm install --no-optional`. The new dependencies are now loaded via `require` so as to get around the ES6 static analysis requirement for module imports.

**Comment by kavanagh** [comment]
This ensures the optional deps are not installed automatically: https://github.com/ft-interactive/starter-kit/commit/4c60498086700e2209c4bc1269283fc8c0ce9f39

**Comment by aendrew** [comment]
Rebased against `master`.

**Comment by aendrew** [comment]
Have also added a check that prevents running preflight on initial build.

**Pull request merged**
