### PR TITLE
🔥🔥🔥 Kills Nightwatch/Selenium with fire 🔥🔥🔥

### PR DESCRIPTION
**Pull request by aendrew**
Replaces with ~~Karma +~~ Mocha + Chai ~~+ Headless Chrome.~~ + JSDom

I initially had Karma but then realised we're just checking the existence of elements in raw HTML so why not just use JSDom, lose some dependencies, and speed stuff up in the process?

### CODE REVIEW

**Comment by aendrew** [comment]
Welp, almost working — just needs to get `CHROME_BIN` env var set.

**Comment by aendrew** [comment]
Removing Karma because it's overkill, and I'd need to do some dumb stuff with `docker-compose` to get headless Chrome and Node in the same image. I've replaced it with JSDom, which is ✨ splendid! ✨

**Comment by callumlocke** [comment]
@aendrew could you also (maybe in another PR) remove all references to the name "preflight", and rename to something like "auto-qa" or "qa-checks" or something? Open to suggestions

**Comment by aendrew** [comment]
@callumlocke Yeah, absolutely; the name has bugged me for ages. 

Thanks for the review, have rebased and merged both commits — decided not to squash the first one out of existence in case we ever do need in-browser testing, at which point we can just cherry-pick 21124a565e166f7335e0e9a1ea8a036b4e7079b0.

**Pull request merged**
