### PR TITLE
🌟 new: Adds preflight tests via Nightwatch

### PR DESCRIPTION
**Pull request by aendrew**
This adds Nightwatch/Selenium and has about ~50 assertions to check the main meta tags are all filled.

### CODE REVIEW

**Comment by aendrew** [comment]
Have pushed a new commit that temporarily replaces gulp-sass with `aendrew/gulp-sass`, which merely updates `node-sass` to version >=3.7.0 (and thus works in Node v6). 

The failing tests above are expected as the default starter kit code doesn't have any of those values enabled. I need to find a way of testing whether the repo being built is `*/starter-kit` and then bypassing preflight if that is indeed the case.

**Comment by kavanagh** [comment]
Could you rebase this to starter-kit#master.

Also, it's fine to work in the main repo, rather than in forks.

**Comment by kavanagh** [comment]
Re Sass version: https://github.com/dlmanning/gulp-sass/issues/503

**Comment by aendrew** [comment]
Erp. Did not do that properly... Let me retry...

**Comment by aendrew** [comment]
Closing this because I've redone my changes on a new branch that hasn't diverged as far as `ig-article` did.

**Pull request closed without merging**
