### PR TITLE
Upgrade to new FT colour palette

### LINKED ISSUE #128: Change Old Pink to the New Pink
The old pink is #fff1e0
Search and replace to #fff1e5

### PR DESCRIPTION
**Pull request by callumlocke**
Fixes #128. This upgrades **all** Origami deps to their latest versions, and makes a few corresponding changes to our classnames and stuff.

[Trello ticket](https://trello.com/c/kEZAfW4p/44-update-origami-deps-starter-kit117)

[Live preview](http://ft-ig-content-prod.s3-website-eu-west-1.amazonaws.com/v2/ft-interactive/starter-kit/upgrade-to-o-colors-4/)

### CODE REVIEW

**Comment by callumlocke** [comment]
I've done the easy bit: update to the latest version of every Origami component. So our build service URL is now getting the latest version of pretty much everything. But I have not yet verified that starter-kit is still fully compatible with these new modules.

Most of the Origami modules have received major version bumps. Hopefully in most cases this is just because they no longer support `o-colors < 4`,  in which case we shouldn't need to do anything more. But in some cases, a module might have received other breaking changes. So we need to check all their release notes and see if anything applies to us.

Here's a checklist:

- [ ] o-fonts@^3.0.1
- [ ] o-typography@^5.1.1
- [ ] o-header@^7.0.4
- [ ] o-card@^3.0.0
- [ ] o-footer@^6.0.2
- [ ] o-comments@^4.0.2
- [ ] o-share@^5.0.0
- [ ] o-ads@^6.1.5

Also ideally someone should make a new starter-kit project (from this branch) and enable all the various config options to get a full build service URL, and then manually check for issues.

**Comment by alicebartlett** [comment]
(With the exception of fonts, comments and ads, all of these components have migration guides in their README)

- Fonts has only removed Benton and Miller so you should be fine
- Typography has deprecated quite a lot of stuff and renamed some other things, a full migration guide is here: https://github.com/financial-times/o-typography#migrating-from-v4-to-v5
- No other breaking changes to header
- No other breaking changes to card
- No other breaking changes to footer
- No other breaking changes to comments
- o-share looks like it has a few class names renamed: https://github.com/financial-times/o-share#migrating-from-v4xx-to-v5xx
- Looks like there are no breaking changes for o-ads

**Comment by callumlocke** [comment]
Live preview at http://ft-ig-content-prod.s3-website-eu-west-1.amazonaws.com/v2/ft-interactive/starter-kit/upgrade-to-o-colors-4/

**Comment by callumlocke** [comment]
This is ready for review now.

**Comment by ajwl** [comment]
Hey so this all looks fine when rendered. 

But there's a road bump when I pull down this branch and run npm install. I get this message 
```
> undefined postinstall /Users/anna.leach/projects/starter-kit
> bower install --allow-root

bower cached        https://github.com/Financial-Times/o-colors.git#3.6.0
bower validate      3.6.0 against https://github.com/Financial-Times/o-colors.git#^3.6.0
bower cached        https://github.com/Financial-Times/o-colors.git#3.6.0
bower validate      3.6.0 against https://github.com/Financial-Times/o-colors.git#^3.0.0
bower cached        https://github.com/Financial-Times/o-colors.git#3.6.0
bower validate      3.6.0 against https://github.com/Financial-Times/o-colors.git#^3.3.2
bower cached        https://github.com/Financial-Times/o-colors.git#4.1.1
bower validate      4.1.1 against https://github.com/Financial-Times/o-colors.git#^4.1.1

Unable to find a suitable version for o-colors, please choose one by typing one of the numbers below:
    1) o-colors#^3.0.0 which resolved to 3.6.0 and is required by o-ads#6.1.5
    2) o-colors#^3.3.2 which resolved to 3.6.0 and is required by o-visual-effects#1.0.0
    3) o-colors#^3.6.0 which resolved to 3.6.0 and is required by o-share#3.2.2
    4) o-colors#^4.1.1 which resolved to 4.1.1 and is required by starter-kit
```
It works by typing 4 but can we set this in the code to avoid confusing users?

How about also upgrading o-ads and o-share to the latest versions and putting them in `bower.json`? Since we have to use them anyway

**Comment by alicebartlett** [comment]
This is probably happening because bower is 'helpfully' using your local file system to see if it already has components installed and then not using the most up to date ones specified by the bower.json. To check this you can delete your bower_components file and then install again.

**Comment by ajwl** [comment]
👌  that fixes it. 
Final question - if we're updating origami deps to the latest version, why are we not updating eg. o-ads to 7.0.0, which is the latest version?

**Comment by alicebartlett** [comment]
Oh! Yes you should update to the latest o-ads, unless @callumlocke  has a reason not to, 6.1.5 -> 7.0.0 is just major version bumps so should be safe

**Comment by callumlocke** [comment]
I think I've caused confusion by from my comment above, where I wrote the wrong o-ads version number. The PR does update both CSS and JS build service URLs to o-ads 7.0.0.

**Pull request merged**
